### PR TITLE
Incomplete Adding of new ROMs done. Also Fixed some typos and also ex…

### PR DESCRIPTION
**Pull request by msfjarvis**
…perimentally used text input for branch selection process.

### CODE REVIEW

**Comment by msfjarvis** [comment]
Merge this one in and GUI-fy it. We'll then finish it up and rock the scene ;) @AndroGeek974

**Comment by faddat** [comment]
I'm forking the master to merge this @MSF-Jarvis.  Then I'm going to run it and figure out where the collaborative magic can happen...

**Comment by msfjarvis** [comment]
That's great @faddat, coz @AndroGeek974's gone NORDO. It's nice to see someone taking the initiative. I'm free for today and tomorrow, so if you need help, just PM me over at XDA. See ya!!!

**Comment by faddat** [comment]
do you Skype at all, Harsh?  I hate using web forms to have conversations.
Let's talk about what we think this should be, spec it out, and build it
over the next month, yeah?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by msfjarvis** [comment]
On 21/11/2015, Jacob Gadikian notifications@github.com wrote:

> do you Skype at all, Harsh?  I hate using web forms to have conversations.
> Let's talk about what we think this should be, spec it out, and build it
> over the next month, yeah?
> 
> Jacob Gadikian
> E-mail: faddat@gmail.com
> SKYPE: faddat
> Phone/SMS: +84 167 789 6421
> 
> On Sat, Nov 21, 2015 at 9:24 AM, Harsh Shandilya notifications@github.com
> wrote:
> 
> > That's great @faddat https://github.com/faddat, coz @AndroGeek974
> > https://github.com/AndroGeek974's gone NORDO. It's nice to see someone
> > taking the initiative. I'm free for today and tomorrow, so if you need
> > help, just PM me over at XDA. See ya!!!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/AndroGeek974/AndroidAutoCompiler/pull/1#issuecomment-158577788
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AndroGeek974/AndroidAutoCompiler/pull/1#issuecomment-158645083

I do, I do but I haven't been getting much time. I also have to work
on the GUI of a school project, also written in Python. Maybe tomorrow

## (22.11.2015) I'll have a chitchat with you over at Skype.

MSF Jarvis
Senior Member
XDA-Developers.com(@ MSF Jarvis)

**Pull request merged**
